[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm ci --omit=dev"]

# Skip build phase - GitHub Actions already pre-rendered the files
# [phases.build]
# cmds = ["npm run build"]

[start]
cmd = "npm run serve"
