[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm ci --omit=dev"]

# Skip build phase - Files are pre-rendered locally and committed to repo
# [phases.build]
# cmds = ["npm run build"]

[start]
cmd = "npm run serve"
